layout_spectrum: 0.034978032506043366
typography_spectrum: 0.17247697888569224
color:
  brandStrength: 0.6394064299897798
  lightness: 0.7949118068631702
  saturation: 0.6900173379044684
  rhythmicContrast: 0.6647020082624795
  brandColors:
    - '#F4F2ED'
    - '#FBF9F1'
    - '#FDFDF9'
    - '#F0ECE8'
    - '#FFFFFF'
colors:
  brandColors:
    - 'hsl(0,0%,100%)'
    - 'hsl(0,0%,80%)'
    - 'hsl(0,0%,60%)'
    - 'hsl(0,0%,30%)'
    - 'hsl(0,0%,20%)'
name: ' '
content: []
title: ''
description: ''
purpose:
  - type: external
    url: 'https://thegrid.ai/contactmkr'
    label: Contact Us
  - type: external
    url: 'https://thegrid.ai/blogmkr'
    label: The Blog
url: 'https://thegrid.ai/storemkr/'
favicon: >-
  https://the-grid-user-content.s3-us-west-2.amazonaws.com/1f3aa8de-d785-438d-9896-d638c3117c2c.png
github: true
logo: >-
  https://the-grid-user-content.s3-us-west-2.amazonaws.com/51ae652e-7dc8-4dd9-a0f7-8ec6eddc7c4c.png
